# Generated by Django 4.0.6 on 2022-07-16 13:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fechaCreacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fechaLastUpdate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_categoria', to='infraestructure.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', django_fsm.FSMIntegerField(choices=[(0, 'Creado'), (1, 'Pagado'), (2, 'Pago Aceptado'), (3, 'Entregado'), (-1, 'Pago Rechazado'), (-2, 'Anulado')], default=0, protected=True)),
                ('total', models.IntegerField(default=0)),
                ('nombre_factura', models.CharField(default='Sin nombre', max_length=200)),
                ('nit_factura', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregado', models.IntegerField(blank=True, default=0)),
                ('emitido', models.IntegerField(blank=True, default=0)),
                ('fechaLastUpdate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_stock', to='infraestructure.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoPagado', models.IntegerField(default=0)),
                ('estado', django_fsm.FSMIntegerField(choices=[(0, 'Pendiente'), (1, 'Pagado'), (2, 'Pago Aceptado'), (-1, 'Anulado')], default=0, protected=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_venta', to='infraestructure.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('precioVenta', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_detalle', to='infraestructure.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta_detalle', to='infraestructure.venta')),
            ],
        ),
    ]
