# Generated by Django 4.0.6 on 2022-07-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fechaLastUpdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
