# Generated by Django 4.0.6 on 2022-07-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructure', '0002_alter_categoria_fechacreacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='fechaCreacion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='fechaLastUpdate',
        ),
    ]
