# Generated by Django 4.0.6 on 2022-07-16 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructure', '0003_remove_categoria_fechacreacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='fechaCreacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fechaLastUpdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
