# Generated by Django 4.0.6 on 2022-07-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructure', '0004_categoria_fechacreacion_categoria_fechalastupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='montoPagado',
        ),
    ]
