# Generated by Django 4.0.6 on 2022-07-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructure', '0005_remove_pago_montopagado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
