# Generated by Django 4.0.6 on 2022-07-16 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructure', '0007_stock_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='fechaLastUpdate',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='stock',
            new_name='stockActual',
        ),
    ]
